### ISSUE TITLE
how do i specify a masterkey

### ISSUE THREAD

**Issue by jesperordrup** [dokku/dokku-meilisearch#17]
when installing meilisearch manually you can specify the master-key as a parameter

./meilisearch --master-key="asfkjsdflkas84"

How do you do it here?

**Comment by josegonzalez** [comment]
We generate a password on service creation and specify that as `MEILI_MASTER_KEY` to the meilisearch container. You can get that from a `dokku meilisearch:info $SERVICE` call.

There is no way at this time to change that master key to something else.

**Comment by paulchubatyy** [comment]
@josegonzalez 
```
$ dokku meilisearch:info staging-test
=====> staging-test meilisearch service information
       Config dir:          /var/lib/dokku/services/meilisearch/staging-test/data
       Config options:
       Data dir:            /var/lib/dokku/services/meilisearch/staging-test/data
       Dsn:                 http://:9a801d3c9b4d69f496bd9da1dd06d161@dokku-meilisearch-staging-test:7700
       Exposed ports:       -
       Id:                  8ecc5d158f5d6186b74e12f9fcc6c64ec3876f54ca7810f0d9f05437f2b09feb
       Internal ip:         172.17.0.9
       Initial network:
       Links:               -
       Post create network:
       Post start network:
       Service root:        /var/lib/dokku/services/meilisearch/staging-test
       Status:              running
       Version:             getmeili/meilisearch:v1.3.5
```

`MEILI_MASTER_KEY` is not exposed in the `info`. =(

**Comment by josegonzalez** [comment]
It's in the Dsn. Specifically, it should be `9a801d3c9b4d69f496bd9da1dd06d161`.

**Comment by paulchubatyy** [comment]
Indeed. I also had to remove the secret key from the `MEILISEARCH_URL` to make it work.

**Comment by undercontr** [comment]
Is it possible to provide two env vars on linking process with stripping master key from the URL and add it as "{ALIAS}_MASTER_KEY" as a second env var along with clean "{ALIAS}_URL" ?

**Comment by josegonzalez** [comment]
I mentioned this on slack (discord?) but this seems to be a failing of the client. Specifically in @undercontr's case, node fetch refuses to use URLs with basic auth in the url, and requires that users remove them and set them as a header. Not sure why it doesn't just parse it out and set the header itself, but here we are.

For various reasons, Dokku datastore plugins don't support multiple env vars today. I have a setup that copies a lot of the logic between plugins, and making a one-off change for meilisearch would make maintenance difficult for the dozen or so datastores we support.

Maybe in the future this will be easier to do with the introduction of [dokku-service](https://github.com/dokku/dokku-service), but for now, I won't be implementing this functionality. I recommend parsing the DSN and constructing a URL that works for your client for now.

**Comment by undercontr** [comment]
@josegonzalez I modified the URL inside the code to be able to work with it. Currently not a blocking issue. Thanks again for explanation on the Discord and here.
