### ISSUE TITLE
Expose meilisearch service over HTTPS

### ISSUE THREAD

**Issue by ikiba-store** [dokku/dokku-meilisearch#60]
Is it possible to expose the service over HTTPS? Thank you very much.

**Comment by josegonzalez** [comment]
You can use this project to do so: https://github.com/dokku/service-proxy

**Comment by ikiba-store** [comment]
Thank yo so much @josegonzalez, it works 😄

**Comment by ikiba-store** [comment]
Thank yo so much @josegonzalez, it works 😄
